// 3  : extremlywide 
// 4  : extremlynarrow
// 5  : imagefont
var serif_subcat = [
['Ultra','2'],
['Holtwood One SC','2'],
['BioRhyme Expanded','2']
]
var mono_subcat = [
['Nova Mono','2'],
['Major Mono Display','2']
]
var sansserif_subcat = [
['Syncopate','2'],
['Seymour One','2'],
['Rubik Mono One','2'],
['Orbitron','2'],
['Notable','2'],
['Montserrat Subrayada','2'],
['Lacquer','2'],
['Black And White Picture','2'],
['Aclonica','2'],
['Wendy One','2']
]
var handwriting_subcat = [
	['Zhi Mang Xing','2'],
	['Zeyada','2'],
	['Yesteryear','6'],
	['Yellowtail','2'],
	['Walter Turncoat','2'],
	['Waiting for the Sunrise','2'],
	['Vibur','2'],
	['Tillana','2'],
	['The Girl Next Door','1'],
	['Tangerine','6'],
	['Swanky and Moo Moo','2'],
	['Sunshiney','2'],
	['Sue Ellen Francisco','6'],
	['Stalemate','2'],
	['Sriracha','1'],
	['Sofia','1'],
	['Short Stack','1'],
	['Shadows Into Light Two','1'],
	['Shadows Into Light','1'],
	['Sedgwick Ave Display','1'],
	['Sedgwick Ave','1'],
	['Schoolbell','1'],
	['Satisfy','2'],
	['Sacramento','2'],
	['Ruthie','2'],
	['Ruge Boogie','2'],
	['Rouge Script','6'],
	['Romanesco','2'],
	['Rock Salt','2'],
	['Rochester','6'],
	['Reenie Beanie','6'],
	['Redressed','1'],
	['Rancho','1'],
	['Qwigley','6'],
	['Quintessential','1'],
	['Princess Sofia','6'],
	['Pinyon Script','6'],
	['Petit Formal Script','1'],
	['Permanent Marker','2'],
	['Patrick Hand SC','1'],
	['Patrick Hand','1'],
	['Parisienne','6'],
	['Pangolin','1'],
	['Pacifico','1'],
	['Over the Rainbow','1'],
	['Nothing You Could Do','2'],
	['Norican','1'],
	['Niconne','1'],
	['Neucha','1'],
	['Nanum Pen Script','1'],
	['Nanum Brush Script','1'],
	['Mrs Sheppards','6'],
	['Mrs Saint Delafield','6'],
	['Mr De Haviland','6'],
	['Mr Dafoe','6'],
	['Mr Bedfort','6'],
	['Montez','2'],
	['Monsieur La Doulaise','6'],
	['Molle','1'],
	['Miss Fajardose','6'],
	['Merienda One','1'],
	['Merienda','1'],
	['Meie Script','2'],
	['Meddon','2'],
	['Marck Script','1'],
	['Mansalva','1'],
	['Mali','1'],
	['Ma Shan Zheng','2'],
	['Lovers Quarrel','6'],
	['Loved by the King','1'],
	['Long Cang','1'],
	['Liu Jian Mao Cao','1'],
	['Leckerli One','1'],
	['League Script','1'],
	['Lateef','1'],
	['Lakki Reddy','1'],
	['La Belle Aurore','1'],
	['Kristi','2'],
	['Kavivanar','1'],
	['Kaushan Script','1'],
	['Kalam','1'],
	['Just Me Again Down Here','1'],
	['Just Another Hand','1'],
	['Julee','1'],
	['Jim Nightshade','1'],
	['Itim','1'],
	['Italianno','1'],
	['Indie Flower','1'],
	['Homemade Apple','2'],
	['Hi Melody','1'],
	['Herr Von Muellerhoff','6'],
	['Handlee','1'],
	['Great Vibes','2'],
	['Grand Hotel','2'],
	['Gochi Hand','1'],
	['Gloria Hallelujah','1'],
	['Give You Glory','2'],
	['Gamja Flower','1'],
	['Gaegu','1'],
	['Fondamento','1'],
	['Felipa','1'],
	['Euphoria Script','2'],
	['Engagement','2'],
	['East Sea Dokdo','2'],
	['Eagle Lake','1'],
	['Dr Sugiyama','6'],
	['Dokdo','2'],
	['Devonshire','1'],
	['Delius Unicase','1'],
	['Delius Swash Caps','1'],
	['Delius','1'],
	['Dekko','1'],
	['Dawning of a New Day','6'],
	['Dancing Script','2'],
	['Damion','2'],
	['Crafty Girls','2'],
	['Covered By Your Grace','2'],
	['Courgette','1'],
	['Cookie','2'],
	['Condiment','1'],
	['Coming Soon','1'],
	['Clicker Script','1'],
	['Chilanka','1'],
	['Charmonman','2'],
	['Charm','2'],
	['Cedarville Cursive','6'],
	['Caveat Brush','1'],
	['Caveat','1'],
	['Calligraffitti','2'],
	['Butterfly Kids','6'],
	['Bonbon','2'],
	['Bilbo Swash Caps','2'],
	['Bilbo','2'],
	['Beth Ellen','6'],
	['Berkshire Swash','1'],
	['Bad Script','1'],
	['Arizonia','6'],
	['Architects Daughter','1'],
	['Annie Use Your Telescope','1'],
	['Amita','1'],
	['Amatic SC','2'],
	['Allura','2'],
	['Alex Brush','2'],
	['Aladin','1'],
	['Aguafina Script','2']
]
var display_subcat = [
	['Zilla Slab Highlight','2'],
	['ZCOOL QingKe HuangYou','1'],
	['ZCOOL KuaiLe','2'],
	['Yeseva One','1'],
	['Yeon Sung','1'],
	['Yatra One','1'],
	['Wellfleet','1'],
	['Warnes','5'],
	['Wallpoet','2'],
	['Voces','1'],
	['Vibes','2'],
	['Vast Shadow','2'],
	['Vampiro One','1'],
	['Unlock','1'],
	['Unkempt','1'],
	['UnifrakturMaguntia','2'],
	['UnifrakturCook','1'],
	['Unica One','1'],
	['Underdog','1'],
	['Uncial Antiqua','2'],
	['Turret Road','1'],
	['Tulpen One','1'],
	['Trochut','1'],
	['Trade Winds','1'],
	['Titan One','1'],
	['Taprom','1'],
	['Suwannaphum','1'],
	['Supermercado One','1'],
	['Stint Ultra Expanded','1'],
	['Stint Ultra Condensed','1'],
	['Stardos Stencil','1'],
	['Stalinist One','3'],
	['Staatliches','1'],
	['Srisakdi','1'],
	['Squada One','1'],
	['Spirax','1'],
	['Spicy Rice','1'],
	['Special Elite','1'],
	['Sonsie One','1'],
	['Sofadi One','1'],
	['Snowburst One','1'],
	['Sniglet','1'],
	['Smythe','1'],
	['Smokum','2'],
	['Slackey','2'],
	['Skranji','1'],
	['Sirin Stencil','1'],
	['Single Day','1'],
	['Simonetta','1'],
	['Sigmar One','1'],
	['Siemreap','1'],
	['Shrikhand','1'],
	['Shojumaru','2'],
	['Share','1'],
	['Sevillana','1'],
	['Seaweed Script','2'],
	['Sarina','2'],
	['Sancreek','2'],
	['Salsa','1'],
	['Saira Stencil One','1'],
	['Sail','1'],
	['Rye','1'],
	['Ruslan Display','2'],
	['Risque','1'],
	['Righteous','1'],
	['Ribeye Marrow','1'],
	['Ribeye','1'],
	['Revalia','1'],
	['Ravi Prakash','2'],
	['Ranga','1'],
	['Ranchers','1'],
	['Rammetto One','1'],
	['Raleway Dots','1'],
	['Rakkas','1'],
	['Racing Sans One','1'],
	['Purple Purse','1'],
	['Prosto One','1'],
	['Press Start 2P','1'],
	['Preahvihear','1'],
	['Poor Story','1'],
	['Pompiere','1'],
	['Poller One','1'],
	['Poiret One','2'],
	['Playball','2'],
	['Plaster','5'],
	['Pirata One','1'],
	['Piedra','1'],
	['Peralta','2'],
	['Patua One','1'],
	['Passion One','1'],
	['Passero One','1'],
	['Paprika','1'],
	['Overlock SC','1'],
	['Overlock','1'],
	['Original Surfer','1'],
	['Oregano','1'],
	['Oleo Script Swash Caps','1'],
	['Oleo Script','1'],
	['Oldenburg','1'],
	['Offside','1'],
	['Odor Mean Chey','1'],
	['Odibee Sans','1'],
	['Nova Square','1'],
	['Nova Slim','1'],
	['Nova Script','1'],
	['Nova Round','1'],
	['Nova Oval','1'],
	['Nova Flat','1'],
	['Nova Cut','1'],
	['Nosifer','5'],
	['Nixie One','1'],
	['New Rocker','1'],
	['Mystery Quest','2'],
	['Mountains of Christmas','2'],
	['Moulpali','1'],
	['Moul','1'],
	['Monoton','2'],
	['Monofett','5'],
	['Mogra','1'],
	['Modern Antiqua','1'],
	['Modak','1'],
	['Mirza','1'],
	['Miniver','2'],
	['Miltonian Tattoo','1'],
	['Miltonian','2'],
	['Milonga','1'],
	['Metamorphous','1'],
	['Metal Mania','2'],
	['Metal','1'],
	['Megrim','2'],
	['Medula One','1'],
	['MedievalSharp','1'],
	['McLaren','1'],
	['Margarine','1'],
	['Maiden Orange','1'],
	['Macondo Swash Caps','1'],
	['Macondo','1'],
	['Luckiest Guy','2'],
	['Love Ya Like A Sister','2'],
	['Londrina Solid','1'],
	['Londrina Sketch','2'],
	['Londrina Shadow','2'],
	['Londrina Outline','2'],
	['Lobster Two','2'],
	['Lobster','2'],
	['Limelight','1'],
	['Lily Script One','2'],
	['Lilita One','1'],
	['Life Savers','1'],
	['Libre Barcode 39 Text','1'],
	['Libre Barcode 39 Extended Text','1'],
	['Libre Barcode 39 Extended','1'],
	['Libre Barcode 39','1'],
	['Libre Barcode 128 Text','1'],
	['Libre Barcode 128','1'],
	['Lemonada','1'],
	['Lemon','1'],
	['Lancelot','1'],
	['Lalezar','1'],
	['Kumar One Outline','2'],
	['Kumar One','1'],
	['Kranky','2'],
	['Koulen','1'],
	['Knewave','1'],
	['Kirang Haerang','2'],
	['Khmer','1'],
	['Kenia','1'],
	['Kelly Slab','1'],
	['Keania One','1'],
	['Kdam Thmor','1'],
	['Kavoon','1'],
	['Katibeh','1'],
	['Joti One','2'],
	['Jomhuria','1'],
	['Jolly Lodger','2'],
	['Jacques Francois Shadow','2'],
	['Irish Grover','2'],
	['Iceland','1'],
	['Iceberg','1'],
	['Henny Penny','1'],
	['Happy Monkey','1'],
	['Hanalei Fill','2'],
	['Hanalei','2'],
	['Gugi','2'],
	['Gruppo','2'],
	['Griffy','2'],
	['Gravitas One','2'],
	['Graduate','2'],
	['Gorditas','2'],
	['Goblin One','2'],
	['Glass Antiqua','1'],
	['Girassol','1'],
	['Germania One','2'],
	['Geostar Fill','2'],
	['Geostar','3'],
	['Galindo','2'],
	['Galada','1'],
	['Fugaz One','1'],
	['Fruktur','1'],
	['Frijole','2'],
	['Freehand','1'],
	['Fredoka One','1'],
	['Fredericka the Great','1'],
	['Freckle Face','1'],
	['Forum','1'],
	['Fontdiner Swanky','2'],
	['Flavors','2'],
	['Flamenco','1'],
	['Finger Paint','2'],
	['Federant','1'],
	['Faster One','5'],
	['Fascinate Inline','5'],
	['Fascinate','5'],
	['Farsan','1'],
	['Expletus Sans','1'],
	['Ewert','2'],
	['Erica One','2'],
	['Emilys Candy','1'],
	['Emblema One','1'],
	['Elsie Swash Caps','1'],
	['Elsie','1'],
	['Eater','1'],
	['Dynalight','2'],
	['Diplomata SC','3'],
	['Diplomata','3'],
	['Dangrek','1'],
	['Cute Font','1'],
	['Crushed','2'],
	['Croissant One','1'],
	['Creepster','2'],
	['Corben','1'],
	['Contrail One','1'],
	['Content','1'],
	['Concert One','1'],
	['Comfortaa','1'],
	['Combo','1'],
	['Coiny','1'],
	['Codystar','2'],
	['Coda','1'],
	['Cinzel Decorative','1'],
	['Chonburi','1'],
	['Chicle','1'],
	['Chewy','1'],
	['Cherry Swash','1'],
	['Cherry Cream Soda','2'],
	['Chenla','1'],
	['Chelsea Market','1'],
	['Chela One','1'],
	['Chango','1'],
	['Changa One','1'],
	['Ceviche One','2'],
	['Carter One','1'],
	['Calistoga','1'],
	['Caesar Dressing','2'],
	['Cabin Sketch','1'],
	['Butcherman','2'],
	['Bungee Shade','2'],
	['Bungee Outline','2'],
	['Bungee Inline','2'],
	['Bungee Hairline','2'],
	['Bungee','2'],
	['Buda','1'],
	['Bubblegum Sans','1'],
	['Bowlby One SC','1'],
	['Bowlby One','1'],
	['Boogaloo','1'],
	['Bokor','1'],
	['Black Ops One','1'],
	['Bigshot One','1'],
	['Bigelow Rules','2'],
	['Big Shoulders Text','1'],
	['Big Shoulders Display','1'],
	['Bevan','1'],
	['Bebas Neue','1'],
	['Bayon','1'],
	['Baumans','1'],
	['Battambang','1'],
	['Barrio','2'],
	['Barriecito','2'],
	['Bangers','1'],
	['Baloo Thambi','1'],
	['Baloo Tammudu','1'],
	['Baloo Tamma','1'],
	['Baloo Paaji','1'],
	['Baloo Da','1'],
	['Baloo Chettan','1'],
	['Baloo Bhaina','1'],
	['Baloo Bhaijaan','1'],
	['Baloo Bhai','1'],
	['Baloo','1'],
	['Bahianita','2'],
	['Bahiana','2'],
	['Averia Serif Libre','1'],
	['Averia Sans Libre','1'],
	['Averia Libre','1'],
	['Averia Gruesa Libre','1'],
	['Autour One','1'],
	['Audiowide','1'],
	['Aubrey','1'],
	['Atomic Age','2'],
	['Atma','1'],
	['Astloch','2'],
	['Asset','3'],
	['Arima Madurai','1'],
	['Arbutus','1'],
	['Angkor','1'],
	['Amarante','1'],
	['Almendra Display','2'],
	['Allan','1'],
	['Alfa Slab One','2'],
	['Akronim','2'],
	['Abril Fatface','1']
]